version: '3'
services:
  api:
    ports:
      - "9000:9000"
    env_file:
      - .env
    build:
      context: ./
      args:
        DATABASE_URL: ${DATABASE_URL}
        RIOT_API_KEY: ${RIOT_API_KEY}
